#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
COMMANDS_FILE="${HOME}/.linkbot-workflow-commands.sh"

cat > "${COMMANDS_FILE}" <<EOF
# Generated by ${REPO_ROOT}/scripts/workflow/install-shell-commands.sh

linkbot() {
  if [ "\$#" -gt 0 ] && [ "\$1" = "deploy" ]; then
    shift
    "${REPO_ROOT}/scripts/workflow/linkbot-deploy.sh" "\$@"
    return \$?
  fi
  printf 'Usage: linkbot deploy [options]\n' >&2
  return 2
}
EOF

install_source_line() {
  local rc_file="$1"
  local source_line='source "$HOME/.linkbot-workflow-commands.sh"'
  if [[ ! -f "${rc_file}" ]]; then
    touch "${rc_file}"
  fi
  if ! grep -Fq "${source_line}" "${rc_file}"; then
    printf '\n%s\n' "${source_line}" >> "${rc_file}"
    printf '[INFO] Added command loader to %s\n' "${rc_file}"
  else
    printf '[INFO] Command loader already present in %s\n' "${rc_file}"
  fi
}

install_source_line "${HOME}/.zshrc"
install_source_line "${HOME}/.bashrc"

printf '[INFO] Installed workflow command functions at %s\n' "${COMMANDS_FILE}"
printf '[INFO] Open a new shell (or run: source "%s") to use:\n' "${COMMANDS_FILE}"
printf '       linkbot deploy\n'
